### ISSUE TITLE
Broken if FF 38 (ESR)

### ISSUE THREAD

**Issue by mgius** [Ubersmake/Adventure#1]
FF 38 is the current Extended Support release that corporate drones like myself have installed on their systems.  With FF38 when I click the next choice link FF tries to open the url `choice: name`.  Whatever is supposed to be intercepting the click doesn't seem to be working.

When I click the link I get the following error from somewhere in the minified markdown.js

```
TypeError: a is undefined
```

**Comment by Ubersmake** [comment]
Fixed with [c86d381bf7c11144a9f6e560fa18d9f999d35ff4](https://github.com/Ubersmake/Adventure/commit/c86d381bf7c11144a9f6e560fa18d9f999d35ff4).

Edge was running into a similar issue where it was trying to launch a program for the "choice:" protocol. Replicated in Firefox 44.0.2, which was returning the same TypeError.

Instead of storing the destination in the href, it's now stored in a "choice" attribute. The href is now a plain old hash.

Note to self: branch and pull request next time for issues.
